#!/bin/bash
git archive --format=tar master | gzip -9c | ssh alexa@138.201.36.30 "cd web && tar --directory=./ -xvzf - && composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader"
